name: flutterdesktop
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  bubble: ^1.1.9+1
  outline_material_icons: ^0.1.1
  eva_icons_flutter: ^2.0.0
  chat_bubbles: ^0.7.5
  flutter_chat_bubble: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - images/logo.png
    - images/photo.jpg
    - images/photo1.jpg
    - images/photo2.png
    - images/photo3.jpeg
    - images/photo3.png
    - images/shubie2.png
